---
# tasks file for debops.deploy_keys

- name: Create group
  group:
    name: '{{ item.group|default(item.name) }}'
    system: True
    state: 'present'
  with_items: '{{ deploy_keys_users }}'

- name: Create user, generate ssh keys
  user:
    name: '{{ item.name }}'
    group: '{{ item.group|default(item.name) }}'
    home: '{{ item.home|default(omit) }}'
    system: '{{ item.system|default(omit) }}'
    shell: '{{ item.shell|default(omit) }}'
    createhome: True
    generate_ssh_key: True
    state: 'present'
  with_items: '{{ deploy_keys_users }}'
  register: deploy_key_register_users

- name: Set up bitbucket deploys
  include: 'bitbucket.yml'
  when: ((bitbucket_user|d() and bitbucket_user) and (bitbucket_password|d() and bitbucket_password))
